

			<aside id="AppDrawer" class="mdl-layout__drawer">
				<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
					<header id="AppDrawerHeader" class="mdl-layout__header mdl-layout__header--waterfall mdl-card--expand mdl-shadow--2dp mdl-app-bg--primary mdl-color--grey-300">
						<div class="mdl-layout__header-row mdl-card--expand" style="background: no-repeat center/contain url('assets/imgs/neurogenesis_monogram.php?stroke_brain_width=0&fill_brain_color=fff&fill_text_n_color=fff&stroke_text_n_color=fff'); filter: drop-shadow(-1px -1px 0 silver);">
						<!--<div class="mdl-layout__header-row mdl-card--expand" style="">-->
							<!--
         					<img src="assets/imgs/neurogenesis_monogram.php?stroke_brain_width=0&fill_brain_color=fff&fill_text_n_color=fff&stroke_text_n_color=fff" class="" style="display: block; height: 50%; filter: drop-shadow(-1px -1px 0 silver);" />
                     		-->
						</div>
					</header>
					<section id="AppDrawerContent" class="mdl-layout__content">
						<nav class="mdl-navigation scroll">
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://neurogenesis.biz"
									 id="drawer-link--home">
									<i class="x-icon material-icons">home</i>
									Home
									<span class="byline">
										description for <em>Home </em> link
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://neurogenesis.biz/index.php#about_neurogenesis">
									<!--<i class="x-icon material-icons">shopping_cart</i>-->
									<img src="assets/imgs/neurogenesis_monogram.php" class="app-avatar x-icon" style="filter: grayscale(100%); width: 1.5rem; margin-right: 1rem;" />
									About <em>Neurogenesis</em>
									<span class="byline">
										Description for <em>About Neurogenesis</em> link
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://neurogenesis.biz/index.php#neurogenesis_services">
									<i class="x-icon material-icons">widgets</i>
									Our <em>Services</em>
									<span class="byline">
										Description for <em>Services Offered</em> at Neurogenesis
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://neurogenesis.biz#referrals">
									<i class="x-icon material-icons">language</i>
									<em>Referrals</em>
									<span class="byline">
										Description for <em>Referrals</em> link
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">psychology</span>
									Psychologists
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<!--<i class="x-icon material-icons">chevron_right</i>-->
											<img src="assets/imgs/photos_psychologists_profile/justin_ashokar.jpeg" class="app-avatar x-icon" style="filter: grayscale(100%); width: 2rem; height: 2rem;" />
											Dr. <strong>Justine</strong> Ashokar, PhD
											<span class="byline">
												<em>Registered Psychologist</em>
											</span>
										</a>
									</li>
									<!--
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											<em>ARS</em> Exports
										</a>
									</li>
									-->
								</ul>
							</div>
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">headset_mic</span>
									Helpline
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="tel://+16054840560">
											<i class="x-icon material-icons">phone</i>
											(605) 484-0560
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon fab fa-whatsapp-square"></i>
											(605) 484-0560
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon fab fa-telegram"></i>
											(605) 484-0560
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon fab fa-snapchat"></i>
											(605) 484-0560
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="mailto:wecare@neurogenesis.biz">
											<i class="x-icon material-icons">mail</i>wecare@neurogenesis.biz
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="assets/vcards/neurogenesis.vcard" download>
											<i class="x-icon material-icons">file_download</i>
											Download vCard
										</a>
									</li>
								</ul>
							</div>
						</nav>
					</section>
				</div>
			</aside>