    <header class="app-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
        <div class="mdl-layout__header-row">
        <a href="#" style="text-decoration: none; display: inline-grid; grid-template-columns: auto 1fr; grid-template-rows: 1rem; gap: 0.25rem; outline: 0px dotted silver; left:-1rem; position: relative;">
        	<img src="assets/imgs/neurogenesis_monogram.php" style="height: 2.4rem; grid-column: 1/2;" />
           <div style="whitespace: nowrap;" class="mdl-layout-title mdl-color-text--black">NEURO<strong class="mdl-typography--font-black">GENESIS</strong><span style="transform: rotate(180deg);writing-mode: vertical-lr; font-size: 0.5rem;">LLC</span></div>
           <div style="whitespace: nowrap; grid-column: 2;" class="mdl-color-text--grey">Re-invent You</div>
          </a>
          <div class="mdl-layout-spacer"></div>
          <!--
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
            <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" id="search">
              <label class="mdl-textfield__label" for="search">Enter your query...</label>
            </div>
          </div>
          -->
		  <!--
          <a href="#">
            <img src="assets\imgs\photos_psychologists_profile\justin_ashokar.jpeg"  class="app-avatar" />
          </a>
          -->
          <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
            <li class="mdl-menu__item">About</li>
            <li class="mdl-menu__item">Contact</li>
            <li class="mdl-menu__item">Legal information</li>
          </ul>
          <!--
          <a href="#">
            <img src="assets\imgs\photos_psychologists_profile\justin_ashokar.jpeg"  class="app-avatar" style="margin-right: 0rem;" />
          </a>
          -->
        </div>
      </header>