                <!-- Slider - Start -->
                <section class="swiper-container mdl-color--white">
					<div class="swiper-wrapper">
						<div class="swiper-slide slide-bg--mangoes">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1  class="mdl-typography--text-uppercase swiper-slide-content--headline">
										01
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--pomegrantes">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1  class="mdl-typography--text-uppercase swiper-slide-content--headline">
										0<em>2</em>
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--oranges">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
										<em>0</em>3
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--dates">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
											<em>0</em>4
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--corns">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									<em>0</em> 5
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--honey">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									<em>0</em>6
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--gooseberry">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									<em>0</em>7
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--onions">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									0<em>8</em>s
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--potatoes">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									0<em>9</em>
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--all-vegetables">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									1 <em>0</em> s
								</h1>
							</div>
						</div>
					</div>

					<!-- If we need pagination -->
					<!-- -->
					<div class="swiper-pagination"></div>
					<!-- -->
					<!-- If we need navigation buttons -->
					<!-- -->
					<div class="swiper-button-prev"></div>
					<div class="swiper-button-next"></div>
					<!-- -->

					<!-- If we need scrollbar -->
					<!-- -->
					<div class="swiper-scrollbar"></div>
					<!-- -->
				</section>
                <!-- Slider - End -->