

			<aside id="AppDrawer" class="mdl-layout__drawer">
				<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
					<header id="AppDrawerHeader" class="mdl-layout__header mdl-layout__header--waterfall mdl-card--expand mdl-shadow--2dp mdl-app-bg--primary mdl-color--grey-300">
						<div class="mdl-layout__header-row mdl-card--expand">
							
         					<img src="assets/imgs/neurogenesis_monogram.svg" class="app-avatar" />
                     		
						</div>
					</header>
					<section id="AppDrawerContent" class="mdl-layout__content">
						<nav class="mdl-navigation scroll">
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://raneesfresh.com"
									 id="drawer-link--shop-now">
									<i class="x-icon material-icons">home</i>
									Home
									<span class="byline" style="display: none;">
										for fresh <em>indian fruits, honey &amp; vegetables</em>
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://raneesfresh.com/shoponline">
									<i class="x-icon material-icons">shopping_cart</i>
									<em>Shop</em> Now
									<span class="byline">
										Be Healthy yet <em>pocket friendly</em>
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://wholesale.raneesfresh.com/shoponline">
									<i class="x-icon material-icons">widgets</i>
									Buy <em>Bulk</em>
									<span class="byline">
										For <em>orders above 50kgs</em> per product
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="http://exports.raneesfresh.com/shoponline">
									<i class="x-icon material-icons">language</i>
									<em>Inter</em>national
									<span class="byline">
										For <em>international orders above 50kgs</em> per product
									</span>
								</a>
							</div>
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">headset_mic</span>
									Helpline
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="tel://+919940084365">
											<i class="x-icon material-icons">phone</i>
											[+91] 99400 84365
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon fab fa-whatsapp-square"></i>
											[+91] 99400 84365
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="mailto:wecare@raneesfresh.com">
											<i class="x-icon material-icons">mail</i>wecare@raneesfresh.com
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="RaneesFresh.vcard" download>
											<i class="x-icon material-icons">file_download</i>
											Download vCard
										</a>
									</li>
								</ul>
							</div>
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">psychology</span>
									Psychologists
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Dr. <strong>Justin</strong> Ashokar, PhD
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											<em>ARS</em> Exports
										</a>
									</li>
								</ul>
							</div>
							<!--
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">shopping_cart</span>
									<em>Shop</em> Online
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="http://raneesfresh.com/shoponline">
											<i class="x-icon material-icons">chevron_right</i>
											<em>Shop</em> Now
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Sign-In
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Sign-Up
										</a>
									</li>
								</ul>
							</div>
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">widgets</span>
									Whole<em>sale</em>
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="http://wholesale.raneesfresh.com/shoponline">
											<i class="x-icon material-icons">chevron_right</i>
											Buy <em>Bulk</em>
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Sign-In
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Sign-Up
										</a>
									</li>
								</ul>
							</div>
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">language</span>
									<em>Inter</em>national
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="http://exports.raneesfresh.com/shoponline">
											<i class="x-icon material-icons">chevron_right</i>
											<em>Order</em> Now
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Sign-In
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Sign-Up
										</a>
									</li>
								</ul>
							</div>
							<div class="mdl-navigation__item mdl-navigation__toggle mdl-menu__item--full-bleed-divider">
								<a   class="mdl-navigation__link"
									 href="#">
									<span class="x-icon material-icons">info</span>
									Infos &hellip;
								</a>
								<ul class="mdl-navigation__dropdown">
									<li class="mdl-navigation__item mdl-navigation__toggle">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											About &hellip; Psychologists
										</a>
										<ul class="mdl-navigation__dropdown ml-4">
											<li class="mdl-navigation__item">
												<a   class="mdl-navigation__link"
													 href="#">
													<i class="x-icon material-icons">chevron_right</i>
													<em>Ranee&apos;s</em> Fresh
												</a>
											</li>
											<li class="mdl-navigation__item">
												<a   class="mdl-navigation__link"
													 href="#">
													<i class="x-icon material-icons">chevron_right</i>
													<em>ARS</em> Exports
												</a>
											</li>
										</ul>
								</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Terms of usage
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											Privacy Policy
										</a>
									</li>
									<li class="mdl-navigation__item">
										<a   class="mdl-navigation__link"
											 href="#">
											<i class="x-icon material-icons">chevron_right</i>
											&hellip;
										</a>
									</li>
								</ul>
							</div>
							-->
						</nav>
					</section>
				</div>
			</aside>