                <!-- Slider - Start -->
                <section class="swiper-container mdl-color--white">
					<div class="swiper-wrapper">
						<div class="swiper-slide slide-bg--mangoes">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1  class="mdl-typography--text-uppercase swiper-slide-content--headline">
										Man<em>go</em>es
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--pomegrantes">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1  class="mdl-typography--text-uppercase swiper-slide-content--headline">
										Pomegran<em>ate</em>s
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--oranges">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
										<em>Or</em>anges
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--dates">
							<div class="mdl-grid swiper-slide-content">
								<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
									<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
											<em>Date</em>s
									</h1>
								</div>
							</div>
						</div>
						<div class="swiper-slide slide-bg--corns">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									<em>Sweet</em> Corn / Cobs
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--honey">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									<em>Honey</em>
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--gooseberry">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									<em>Go</em>oseberry
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--onions">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									Oni<em>on</em>s
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--potatoes">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									Pota<em>toes</em>
								</h1>
							</div>
						</div>
						<div class="swiper-slide slide-bg--all-vegetables">
							<div class="mdl-cell mdl-cell--12-col mdl-cell--middle">
								<h1 class="mdl-typography--text-uppercase swiper-slide-content--headline">
									All <em>India</em>n Vegetables
								</h1>
							</div>
						</div>
					</div>

					<!-- If we need pagination -->

					<div class="swiper-pagination"></div>

					<!-- If we need navigation buttons -->
					<!--
					<div class="swiper-button-prev"></div>
					<div class="swiper-button-next"></div>
					-->

					<!-- If we need scrollbar -->
					<!--
					<div class="swiper-scrollbar"></div>
					-->
				</section>
                <!-- Slider - End -->
